version: '3'

tasks:
  default:
    silent: true
    desc: "Show list of all available Taskfile commands"
    cmds:
      - task --list --color

  build:
    desc: "Build Docker image"
    cmds:
      - docker build --no-cache -t playground-vdt182 .

  down:
    desc: "Stop and remove playground container"
    cmds:
      - docker stop playground-vdt182-app
      - docker rm playground-vdt182-app

  up:
    desc: "Start playground container"
    cmds:
      - docker start playground-vdt182-app || docker run -d --name playground-vdt182-app -p 5173:5173 -v ${PWD}:/app playground-vdt182

  logs:
    desc: "Follow logs from the playground container with tail output"
    cmds:
      - docker logs -f --tail 100 playground-vdt182-app

  bash:
    desc: "Open interactive shell session inside the running playground container"
    cmds:
      - docker exec -it playground-vdt182-app sh